# 40-50 million records in Ozone DB
# from https://pgtune.leopard.in.ua/?dbVersion=14&osType=linux&dbType=web&cpuNum=16&totalMemory=40&totalMemoryUnit=GB&connectionNum=20&hdType=ssd&dbSize=mid_ram
# DB Version: 14
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 40 GB
# CPUs num: 16
# Connections num: 20
# Data Storage: ssd

max_connections = 20
shared_buffers = 10GB
effective_cache_size = 30GB
maintenance_work_mem = 2560MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 291271kB
huge_pages = try
jit = off
wal_compression = on
autovacuum_max_workers = 4
autovacuum_work_mem = 2GB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 16
max_parallel_workers_per_gather = 4
max_parallel_workers = 16
max_parallel_maintenance_workers = 4
