name: build-and-push-ghcr-firehose-client
on:
  push:
    branches:
      - main
    tags:
      - firehose-client-v*
env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  # github.repository as <account>/<repo>
  IMAGE_NAME: SteveTownsend/firehose-client

jobs:
  firehose-client-container-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: firehose-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: 'json'
          filters: |
            firehose-client:
              - 'firehose-client/**'
              - 'Dockerfile.firehose_client'
            shared-code:
              - 'include/**'
              - 'source/**'
            shared-build:
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
              - 'spdlogConfig.cmake'

      - name: Setup Docker buildx
        if: steps.filter.outputs.firehose-client == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: steps.filter.outputs.firehose-client == 'true' || steps.filter.outputs.shared-code == 'true' || steps.filter.outputs.shared-build == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Extract Docker metadata
        if: steps.filter.outputs.firehose-client == 'true' || steps.filter.outputs.shared-code == 'true' || steps.filter.outputs.shared-build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long

      - name: Build and push Docker image
        if: steps.filter.outputs.firehose-client == 'true' || steps.filter.outputs.shared-code == 'true' || steps.filter.outputs.shared-build == 'true'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ./Dockerfile.firehose_client
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
